# Generated by Django 2.2.16 on 2022-12-01 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_auto_20221201_1522'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follow',
            options={'ordering': ['-created']},
        ),
    ]
